import Mathlib.RingTheory.Unramified.Field
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.Tactic

/-! A nonsingular polynomial zero is algebraic over its coefficient field.
The proof uses the universal derivation on the field generated by its coordinates. -/

namespace StructuralNote.PolynomialAlgebraicity

open MvPolynomial
open scoped BigOperators
noncomputable section

variable {K L : Type*} [Field K] [Field L] [Algebra K L]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

theorem derivation_aeval {M : Type*} [AddCommGroup M] [Module L M] [Module K M]
    [IsScalarTower K L M] (D : Derivation K L M) (x : ι → L) (p : MvPolynomial ι K) :
    D (aeval x p) = ∑ i, aeval x (pderiv i p) • D (x i) := by
  induction p using MvPolynomial.induction_on with
  | C c => simp
  | add p q hp hq =>
    simp only [map_add, hp, hq, add_smul, Finset.sum_add_distrib]
  | mul_X p j hp =>
    simp only [map_mul, aeval_X, Derivation.leibniz, hp, pderiv_X,
      smul_eq_mul, map_add, Pi.single_apply, apply_ite, map_zero, add_smul, mul_smul,
      ite_smul, zero_smul, Finset.sum_add_distrib, Finset.smul_sum, mul_one, mul_zero]
    simp

theorem matrix_smul_kernel_eq_zero {M : Type*} [AddCommGroup M] [Module L M]
    (A : Matrix ι ι L) (hA : A.det ≠ 0) (v : ι → M)
    (hv : ∀ i, ∑ j, A i j • v j = 0) : ∀ i, v i = 0 := by
  intro i
  calc
    v i = ∑ j, (A⁻¹ * A) i j • v j := by
      rw [Matrix.nonsing_inv_mul A (isUnit_iff_ne_zero.mpr hA)]
      simp [Matrix.one_apply]
    _ = ∑ k, A⁻¹ i k • (∑ j, A k j • v j) := by
      simp only [Matrix.mul_apply, Finset.sum_smul, Finset.smul_sum, mul_smul]
      rw [Finset.sum_comm]
    _ = 0 := by simp [hv]

def jacobian (p : ι → MvPolynomial ι K) (x : ι → L) : Matrix ι ι L :=
  fun i j => aeval x (pderiv j (p i))

theorem derivation_coordinates_zero {M : Type*} [AddCommGroup M] [Module L M] [Module K M]
    [IsScalarTower K L M] (D : Derivation K L M)
    (p : ι → MvPolynomial ι K) (x : ι → L)
    (hp : ∀ i, aeval x (p i) = 0) (hJ : (jacobian p x).det ≠ 0) :
    ∀ i, D (x i) = 0 := by
  apply matrix_smul_kernel_eq_zero (jacobian p x) hJ
  intro i
  change (∑ j, aeval x (pderiv j (p i)) • D (x j)) = 0
  rw [← derivation_aeval, hp, map_zero]

omit [Fintype ι] [DecidableEq ι] in
theorem derivation_zero_of_field_generators {M : Type*} [AddCommGroup M]
    [Module L M] [Module K M] [IsScalarTower K L M]
    (D : Derivation K L M) (x : ι → L)
    (hx : IntermediateField.adjoin K (Set.range x) = ⊤)
    (hD : ∀ i, D (x i) = 0) : ∀ y, D y = 0 := by
  intro y
  have hy : y ∈ IntermediateField.adjoin K (Set.range x) := by rw [hx]; trivial
  induction hy using IntermediateField.adjoin_induction with
  | mem z hz =>
    obtain ⟨i, rfl⟩ := hz
    exact hD i
  | algebraMap c => exact D.map_algebraMap c
  | add a b _ _ ha hb => simp [map_add, ha, hb]
  | inv a _ ha => simp [D.leibniz_inv, ha]
  | mul a b _ _ ha hb => simp [D.leibniz, ha, hb]

theorem isAlgebraic_of_generators (p : ι → MvPolynomial ι K) (x : ι → L)
    (hx : IntermediateField.adjoin K (Set.range x) = ⊤)
    (hp : ∀ i, aeval x (p i) = 0) (hJ : (jacobian p x).det ≠ 0) :
    Algebra.IsAlgebraic K L := by
  let D := KaehlerDifferential.D K L
  have hD : ∀ y, D y = 0 := derivation_zero_of_field_generators D x hx
    (derivation_coordinates_zero D p x hp hJ)
  have hΩ : (⊤ : Submodule L (KaehlerDifferential K L)) ≤ ⊥ := by
    rw [← KaehlerDifferential.span_range_derivation, Submodule.span_le]
    rintro _ ⟨y, rfl⟩
    exact hD y
  let : Algebra.FormallyUnramified K L :=
    ⟨(subsingleton_iff_forall_eq 0).mpr (fun y => hΩ trivial)⟩
  let : Algebra.EssFiniteType K L := IntermediateField.fg_top_iff.mp
    (hx ▸ IntermediateField.fg_adjoin_of_finite (Set.finite_range x))
  let := Algebra.FormallyUnramified.finite_of_free K L
  infer_instance

/-- No isolation or algebraicity hypothesis is needed: the nonzero evaluated
Jacobian determinant of a square polynomial system already forces algebraicity. -/
theorem isAlgebraic_of_nonsingular_zero (p : ι → MvPolynomial ι K) (x : ι → L)
    (hp : ∀ i, aeval x (p i) = 0) (hJ : (jacobian p x).det ≠ 0) :
    ∀ i, IsAlgebraic K (x i) := by
  let F : IntermediateField K L := IntermediateField.adjoin K (Set.range x)
  let y : ι → F := fun i => ⟨x i, IntermediateField.subset_adjoin K _ ⟨i, rfl⟩⟩
  have he (q : MvPolynomial ι K) : F.val (aeval y q) = aeval x q :=
    MvPolynomial.comp_aeval_apply y F.val q
  have hpy : ∀ i, aeval y (p i) = 0 := by
    intro i
    apply F.val.injective
    change F.val (aeval y (p i)) = F.val 0
    rw [he, hp, map_zero]
  have hmap : (jacobian p y).map F.val = jacobian p x := by
    ext i j
    exact he (pderiv j (p i))
  have hJy : (jacobian p y).det ≠ 0 := by
    intro hz
    apply hJ
    rw [← hmap]
    change (F.val.mapMatrix (jacobian p y)).det = 0
    rw [← F.val.map_det, hz, map_zero]
  have hy : IntermediateField.adjoin K (Set.range y) = ⊤ := by
    apply top_unique
    rintro ⟨z, hz⟩ _
    change z ∈ IntermediateField.adjoin K (Set.range x) at hz
    induction hz using IntermediateField.adjoin_induction with
    | mem z hz =>
      obtain ⟨i, rfl⟩ := hz
      exact IntermediateField.subset_adjoin K _ ⟨i, rfl⟩
    | algebraMap c => exact IntermediateField.algebraMap_mem _ c
    | add a b _ _ ha hb => exact add_mem (ha trivial) (hb trivial)
    | inv a _ ha => exact inv_mem (ha trivial)
    | mul a b _ _ ha hb => exact mul_mem (ha trivial) (hb trivial)
  let := isAlgebraic_of_generators p y hy hpy hJy
  intro i
  exact (Algebra.IsAlgebraic.isAlgebraic (y i)).algHom F.val

/-- Algebraic coefficients give coordinates algebraic over the original base field as well. -/
theorem isAlgebraic_over_base_of_nonsingular_zero {F : Type*} [Field F]
    [Algebra F K] [Algebra F L] [IsScalarTower F K L] [Algebra.IsAlgebraic F K]
    (p : ι → MvPolynomial ι K) (x : ι → L)
    (hp : ∀ i, aeval x (p i) = 0) (hJ : (jacobian p x).det ≠ 0) :
    ∀ i, IsAlgebraic F (x i) := by
  intro i
  by_contra hi
  exact ((Algebra.IsAlgebraic.transcendental_iff F K).mp hi)
    (isAlgebraic_of_nonsingular_zero p x hp hJ i)

theorem rational_real_zero_isAlgebraic (p : ι → MvPolynomial ι ℚ) (x : ι → ℝ)
    (hp : ∀ i, aeval x (p i) = 0) (hJ : (jacobian p x).det ≠ 0) :
    ∀ i, IsAlgebraic ℚ (x i) := isAlgebraic_of_nonsingular_zero p x hp hJ

end
end StructuralNote.PolynomialAlgebraicity
